name: Format Blade Files

on: [push]

jobs:
  formatting-blade-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Blade Formatter
        run: node_modules/.bin/blade-formatter --write resources/**/*.blade.php

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Blade Formatter Changes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
